### ISSUE TITLE
你好。运行MAIN.PY后出现以下错误，请问如何解决

### ISSUE THREAD

**Issue by 1010chenhao** [roadwide/WeiBoRelation#2]
Reloaded modules: WEIBO, WEIBO.WEIBO, WEIBO.Find
Traceback (most recent call last):

  File "C:\Users\butters\Desktop\WeiBoRelation-master\main.py", line 11, in <module>
    w.discoverRelation(max_fans=1000)

  File "C:\Users\butters\Desktop\WeiBoRelation-master\WEIBO\WEIBO.py", line 250, in discoverRelation
    self.getRelationData(self.WBID, max_fans=max_fans)

  File "C:\Users\butters\Desktop\WeiBoRelation-master\WEIBO\WEIBO.py", line 238, in getRelationData
    self.get_all_fans(max_fans=max_fans)

  File "C:\Users\butters\Desktop\WeiBoRelation-master\WEIBO\WEIBO.py", line 191, in get_all_fans
    max_turn = self.get_fans_num() // 20 + 1

  File "C:\Users\butters\Desktop\WeiBoRelation-master\WEIBO\WEIBO.py", line 144, in get_fans_num
    fans_num = re.findall(">粉丝\[(.+?)\]<", str(user_div))[0]

IndexError: list index out of range

**Comment by rocket-boom** [comment]
> u

你没有在main里面写用户名密码和要爬的人的id

**Comment by liuyijiang1994** [comment]
login_code 50050011
请问这个code是个啥意思 我试了下好像没有登录成功
{'retcode': 50050011, 'msg': 'login second verify', 'data': {'errurl': 'https://passport.weibo.cn/signin/secondverify/index?id=2NGFfa27yAATfJu5Pc9305E59i6aa-clxBWxvZ2lu', 'errline': 517}}
